name: test-workflows

on:
  push:
    branches:
      - main
    paths:
      - .github/custard/**
      - .github/workflows/**
  pull_request:
    paths:
      - .github/custard/**
      - .github/workflows/**

jobs:
  lint-pass:
    uses: ./.github/workflows/lint.yaml
    with:
      head-sha: ${{ github.event.pull_request.head.sha || github.sha }}
      paths: |
        [
          ".github/custard/test/node/lint-pass",
          ".github/custard/test/python/lint-pass"
        ]

  lint-fail-node:
    uses: ./.github/workflows/lint.yaml
    with:
      head-sha: ${{ github.event.pull_request.head.sha || github.sha }}
      paths: '[".github/custard/test/node/lint-fail"]'
      continue-on-error: true

  check-expected-fails:
    needs: lint-fail-node
    runs-on: ubuntu-latest
    steps:
      - name: Check lint-fail-node (status=${{ needs.lint-fail-node.outputs.status }})
        if: ${{ needs.lint-fail-node.outputs.status == 'failure' }}
        run: exit 1
